### ISSUE TITLE
halts after EULA

### ISSUE THREAD

**Issue by marktheis** [inolen/quakejs#10]
Hi. I'm trying to install the server but nothing happens after I agree with the EULA.

So I do this after cloning the repo:

```
git submodule update --init
npm install
node build/ioq3ded.js +set fs_game baseq3 +set dedicated 2
```
Then I press y and then enter to agree with the EULA. But nothing happens.

I have also tried to manually download the baseq3 content and starting the server with a config like this:
`node build/ioq3ded.js +set fs_game baseq3 +set dedicated 2 +exec server.cfg`
But the same thing happens.

**Comment by pettyalex** [comment]
You need to press enter until it prompts you to *Agree? (y/n)*, then you can enter y and proceed.

**Comment by marktheis** [comment]
Thank you. I did not realise that :)
