### ISSUE TITLE
My own front-end

### ISSUE THREAD

**Issue by migonium** [inolen/quakejs#11]
How i can start my own front-end client? 
In manual there are only way i can start my server to play via http://www.quakejs.com/play?connect%20SERVER_IP:27960

But i want to start my own front-end to play like http://mydomain.com/play?connect%20SERVER_IP:27960.
Is there any solution?

**Comment by begleysm** [comment]
I've written up a detailed guide on installing quakejs under Debian 9/10.  It includes a section on creating your own play page and content server.  Once that is all working locally, getting it to work "on the internet" is simply a matter of setting up port forwards on your router 80 and port 27960.

https://steamforge.net/wiki/index.php/How_to_setup_a_local_QuakeJS_server_under_Debian_9_or_Debian_10
