### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by migonium** [inolen/quakejs#12]
is any setting to provide server with SSL encryption?

**Comment by dj-hedgehog** [comment]
You'd have to add the certificate information in the `createServer`-command in this file: `https://github.com/inolen/quakejs/blob/master/bin/web.js`

Something like
```
var privateKey = fs.readFileSync( 'privatekey.pem' );
var certificate = fs.readFileSync( 'certificate.pem' );

https.createServer({
    key: privateKey,
    cert: certificate
}, app).listen(port);
```
More information: https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

**Comment by migonium** [comment]
Thank you! But there is ws:// protocol used to find dedicated servers and this request fails when server runned over https.
