### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by defanor** [inolen/quakejs#15]
The situation with the license is quite unclear: it seems to be a derivative (port) of a GPLv2-licensed program, and in such a case it should be under GPL. But the github README.md states that the license is MIT, and then the live demo website shows a non-free EULA (probably the original one, by id Software).

Would be nice to clarify and/or fix all that.

**Comment by inolen** [comment]
What's in the readme was originally just in reference to the few files associated with the actual quakejs project, it clearly has no impact on the ioq3 fork.
