### ISSUE TITLE
How do you execute a configuration file?

### ISSUE THREAD

**Issue by anlutro** [inolen/quakejs#16]
I have an existing quake 3 configuration file that I use with ioquake3 as well as CPM - where would I place this file to make it possible to `exec myconfig.cfg`?

Cool project by the way!

**Comment by inolen** [comment]
There's unfortunately not a great way to do this, as all files are inside of paks stored inside of an IndexedDB instance in your browser.

**Comment by zmbbmz** [comment]
quake 3 was and is nearly unplayable not using an own config file. you have to re-change a bunch of binding and commands :/

**Comment by Nakilon** [comment]
https://github.com/inolen/quakejs/issues/28
