### ISSUE TITLE
quakejs demo not running properly because resource was loaded over an insecure channel

### ISSUE THREAD

**Issue by turtleDev** [inolen/quakejs#20]
![ss](https://cloud.githubusercontent.com/assets/12575843/19924425/da1548f0-a111-11e6-90ec-365a2e451266.png)

suggested fix:
```js
xhr.open('GET', '//<uri'); //instead of `http://`
```

**Comment by toxinu** [comment]
Same for me. Chromium 52.

**Comment by inolen** [comment]
Hmph, I'm a bit confused. I don't serve any of quakejs.com over https, yet https is in the play url you have there (chrome 53 here).

**Comment by turtleDev** [comment]
@inolen same with FF v49
![ff](https://cloud.githubusercontent.com/assets/12575843/20039151/63d85a4a-a465-11e6-8e34-dc378120b257.png)

**Comment by turtleDev** [comment]
okay, manually going to `http://quakejs.com` circumvents the problem. I guess your CDN adds https supports, and google by default lists this https url.

**Comment by inolen** [comment]
Ah cheers. Let me try to disable that.

**Comment by inolen** [comment]
Alright, all should be well now.
