### ISSUE TITLE
Calling some code when player gets hurt

### ISSUE THREAD

**Issue by gfwilliams** [inolen/quakejs#25]
Hi,

I've been playing around trying to add 'force feedback' to games with a shock machine controlled via Web Bluetooth, and QuakeJS looked like an awesome game to try and add it to.

Would it be possible for me to add such a thing? Is there anywhere obvious in the code that I could read the current player health from?

I had a quick look around but didn't find anything, and I have a feeling that Q3 uses a virtual machine for the game logic, so I'm not entirely certain if something like the health would be accessible in any meaningful way? The only thing I can think of right now is to try and intercept the draw calls for the HUD, but that's properly hacky.

Sorry for posting this as an 'issue', but I thought the answer might be of interest to others as well.

Thanks!

**Comment by inolen** [comment]
To do this, you would definitely have to modify the game source to call into the appropriate web APIs and recompile.
