### ISSUE TITLE
Online match doesn't load behind https proxy through ws

### ISSUE THREAD

**Issue by kifirkin** [inolen/quakejs#29]
While behind https proxy, can't load online games because website uses websockets `ws`, but could only load through `wss`

**Comment by Hologos** [comment]
I was able to deal with this issue using proxychains. I didn't want to alter the code.

Just install proxychains with package manager, i.e: `yum install proxychains`

The configuration I had to do was in `/etc/proxychains.conf`:

```vim
...
...
[ProxyList]
#socks4         127.0.0.1 9050 # it's important to comment this line

http <ip-of-proxy> <port-of-proxy> <proxy-user> <proxy-password>
```

and just ran the server with:
`proxychains4 node build/ioq3ded.js +set fs_game baseq3 +set dedicated 1 +exec server.cfg`

**Comment by markcs** [comment]
@Hologos  I know this is an old issue, but can you detail what you had in the ProxList to get this working?  Thanks!

**Comment by briancullinan** [comment]
I wrote a SOCKS server to get around this, you can probably connect to was://proxy.quake.games but I modified the client to send a 0x05 network type for connecting outwardly to web sockets, so it won't connect to quakejs servers with this build, but you can use it to connect to UDP servers naturally. `set net_socksEnabled` `net_socksServer` and `net_sockaPort` all have to be set properly.
