### ISSUE TITLE
Can you play on LAN?

### ISSUE THREAD

**Issue by dolohow** [inolen/quakejs#30]

**Comment by dolohow** [comment]
Yes, you can.  Set up dedicated server on your computer and then use link http://www.quakejs.com/play?connect%20YOUR_LAN_IP_ADDRESS:27960

**Comment by begleysm** [comment]
I've created a detailed walk-through on setting a game server, content server, and play page for use in a LAN environment here https://steamforge.net/wiki/index.php?title=How_to_setup_a_local_QuakeJS_server_under_Debian_9

**Comment by begleysm** [comment]
For anyone who is interested, here are instructions on how to get everything running under Windows 10.

https://steamforge.net/wiki/index.php/How_to_setup_a_local_QuakeJS_server_under_Windows_10

**Comment by fenixbul** [comment]
> For anyone who is interested, here are instructions on how to get everything running under Windows 10.
> 
> https://steamforge.net/wiki/index.php/How_to_setup_a_local_QuakeJS_server_under_Windows_10

Is it still available? I'm trying to make Quake3JS playable over LAN or online. Please help me! <3

**Comment by begleysm** [comment]
Yeah sorry about that... I moved across the country and kind borked my server that that was on...  For now here is a link to the Wayback Machine version!

https://web.archive.org/web/20230319034846/https://steamforge.net/wiki/index.php/How_to_setup_a_local_QuakeJS_server_under_Windows_10

And for anyone stumbling across this but looking for Linux here's that guide
https://web.archive.org/web/20230319034832/https://steamforge.net/wiki/index.php/How_to_setup_a_local_QuakeJS_server_under_Debian_9_or_Debian_10

I'll see about adding these links to the various places on the internet that the original (dead link) guides are listed.

**Comment by fenixbul** [comment]
Hey @begleysm, thanks again for the quick response! 😊

I have another question: Is it possible to change the hardcoded content server address (content.quakejs.com)? My goal is to set up a server so that people around the world can connect and play Quake3 on it.

If anyone could assist with this, I’d really appreciate it! Thanks again! 🙏

**Comment by fenixbul** [comment]
Found this: https://github.com/inolen/ioq3/blob/4f7d7bf2159aa0a18b79bb417aa760abac817b2a/code/qcommon/files.c#L3460

**Comment by begleysm** [comment]
It's been a few years.  I honestly don't quite remember why I decided that we had to redirect content.quakejs.com but, as far as I know it's necessary.  The reference you linked is interesting and worth investigating (if you or someone else wants to) but I don't have the time/interest to do so myself right now.

That being said, you are still able to setup a QuakeJS server that anyone in the world can connect to (without messing with content.quakejs.com).  All you need to do is follow the guide, and then make sure that the server is visible to the internet (port forwarding and such) and distribute your IP and/or associated address to whomever you want to.

Here is an example where I am running a quakejs server (using the guide) and you can directly jump into it without using content.quakejs.com): http://steamforge.net:27980
