### ISSUE TITLE
recursive error after: Couldn't compile shader

### ISSUE THREAD

**Issue by Svzem** [inolen/quakejs#53]
This error has appeared after upgrading google chrome to the latest release (Version 75.0.3770.80 (Official Build) (64-bit))

**Comment by MichaelEricOberlin** [comment]
I'm bumping into the same thing; interestingly enough, it works great on Firefox, but not Chrome. I'm specifically running Linux Mint 19, on an AMD FX-8300, with a GTX 950 GPU.
(I _love_ that this works at all though!)
